let mapleader =","

source ~/.vim/plug-config/plugins.vim
source ~/.vim/general/basic.vim

" Keybindings
source ~/.vim/keys/fzf.vim
source ~/.vim/keys/goyo.vim
source ~/.vim/keys/splits.vim
source ~/.vim/keys/shell.vim

" Plugin configs
source ~/.vim/plug-config/lightline.vim
source ~/.vim/plug-config/vimwiki.vim
