#!/bin/sh
draw() {
  ~/.config/lf/draw_img "$@"
  exit 1
}

hash() {
  printf '%s/.cache/lf/%s' "$HOME" \
    "$(stat --printf '%n\0%i\0%F\0%s\0%W\0%Y' -- "$(readlink -f "$1")" | sha256sum | awk '{print $1}')"
}

cache() {
  if [ -f "$1" ]; then
    draw "$@"
  fi
}

file="$1"
shift

if [ -n "$FIFO_UEBERZUG" ]; then
  case "$(file -Lb --mime-type -- "$file")" in
    image/*)
      orientation="$(identify -format '%[EXIF:Orientation]\n' -- "$file")"
      if [ -n "$orientation" ] && [ "$orientation" != 1 ]; then
        cache="$(hash "$file").jpg"
        cache "$cache" "$@"
        convert -- "$file" -auto-orient "$cache"
        draw "$cache" "$@"
      else
        draw "$file" "$@"
      fi
      ;;
    video/*)
      cache="$(hash "$file").jpg"
      cache "$cache" "$@"
      ffmpegthumbnailer -i "$file" -o "$cache" -s 0
      draw "$cache" "$@"
      ;;
	*gz*) tar tzf "$file";;
	*zip|*jar|*war|*ear|*oxt) unzip -l "$file";;
	*bzip*) tar tjf "$file";;
	*xz) xz --list --verbose "$file";;
	*tar) tar tf "$file";;
	*rar) unrar l "$file";;
	*7z*) 7z l "$file";;
    *[1-8]) man "$file" | col -b ;;
    *o) nm "$file" | less ;;
    *torrent) transmission-show "$file";;
    *iso) iso-info --no-header -l "$file";;
    *odt,*ods,*odp,*sxw) odt2txt "$file";;
    *doc) catdoc "$file" ;;
    *docx) docx2txt "$file" - ;;
    *csv) cat "$file" | sed s/,/\\n/g ;;
    #*pdf)
	   #CACHE=$(mktemp /tmp/thumbcache.XXXXX)
	   #pdftoppm -png -singlefile -rx 300 -ry 300 "$file" "$CACHE"
       #draw "$CACHE.png" "$@"
	   #;;
    #*epub)
       #CACHE=$(mktemp /tmp/thumbcache.XXXXX)
       #epub-thumbnailer "$1" "$CACHE" 1024
       #$HOME/.config/lf/image draw "$CACHE" $num 1 $numb $numc
       #;;
	*) highlight --out-format ansi "$file" || cat "$file"
	#*) cat "$file"
	  ;;
  esac
fi

file -Lb -- "$1" | fold -s -w "$width"
exit 0
