#!/bin/sh

# Use neovim for vim if present.
# [ -x '$(command -v nvim)' ] && alias vim='nvim' vimdiff="nvim -d"

# Verbosity and settings that you pretty much just always are going to want.
alias \
	cp='cp -iv' \
	mv='mv -iv' \
	rm='rm -iv' \
	mkd='mkdir -pv' \
	yt='youtube-dl --add-metadata -i' \
	yta='yt -x -f bestaudio/best' \
	ffmpeg='ffmpeg -hide_banner'

# Colorize commands when possible.
alias \
	ls='ls -h --group-directories-first --color=auto' \
	ps_mem='doas ps_mem'
	# grep='grep --color=auto' \
	# diff='diff --color=auto' \
	# ccat='highlight --out-format=ansi' \
	# ip='ip -color=auto'

# These common commands are just too long! Abbreviate them.
alias \
	ka='killall' \
	g='git' \
	f='$FILE' \
	e='$EDITOR' \
	v='$EDITOR' \
	blueup='doas rfkill unblock bluetooth && doas rc-service bluetooth start && doas rc-service bluealsa start' \
	bluedown='doas rfkill block bluetooth && doas rc-service bluetooth stop && doas rc-service bluealsa stop' \
	dotfiles='/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME'

alias \
	tmux='tmux -f ${XDG_CONFIG_HOME:-$HOME/.config}/tmux/tmux.conf' \
	yarn='yarn --use-yarnrc '$XDG_CONFIG_HOME/yarn/config''
