#!/bin/ksh

## doas
set -A complete_doas_1 -- -C -L -a -n -s -u - $(find /usr/bin/ /usr/sbin/ /sbin/ /bin/ $HOME/.local/bin -type f -executable | sed 's/.*\///' )
## rdo
set -A complete_rdo_1 -- $(find /usr/bin/ /usr/sbin/ /sbin/ /bin/ $HOME/.local/bin -type f -executable | sed 's/.*\///' )
## chromium
set -A complete_chromium_1 -- --app --incognito --new-window --no-proxy-server --password-store --proxy-auto-detect --proxy-pac-url --proxy-server --user-data-dir --version
## echo, printf
set -A complete_echo_1 -- $(env | sed 's/=.*//' | sed 's/^/$/') *
set -A complete_printf_1 -- $(env | sed 's/=.*//' | sed 's/^/$/') *
