#!/bin/ksh

stty stop undef     # Disable ctrl-s to freeze terminal.
stty columns 1000

#
export COLUMNS=1000

alias source='.'

## completion
[ -f "${XDG_CONFIG_HOME:-$HOME/.config}/shell/ksh_completion" ] && source "${XDG_CONFIG_HOME:-$HOME/.config}/shell/ksh_completion"

# Load aliases and shortcuts if existent.
[ -f "${XDG_CONFIG_HOME:-$HOME/.config}/shell/aliasrc" ] && source "${XDG_CONFIG_HOME:-$HOME/.config}/shell/aliasrc"

# i am sure there is better way but whatever
PS1="\[\[\033[0;31m\][\[\033[1;33m\]\u\[\033[1;32m\]@\[\033[0;34m\]\h \[\033[0;35m\]\w\[\033[0;31m\]] \[\033[0m\]\$ "

set -o emacs

# vi mode
export KEYTIMEOUT=1

lfcd () {
    tmp="$(mktemp)"
    lf -last-dir-path="$tmp" "$@"
    if [ -f "$tmp" ]; then
        dir="$(cat "$tmp")"
        rm -f "$tmp" >/dev/null
        [ -d "$dir" ] && [ "$dir" != "$(pwd)" ] && cd "$dir"
    fi
}
