let mapleader =","

set runtimepath^=$XDG_CONFIG_HOME/vim
set runtimepath+=$XDG_DATA_HOME/vim
set runtimepath+=$XDG_CONFIG_HOME/vim/after

set packpath^=$XDG_DATA_HOME/vim,$XDG_CONFIG_HOME/vim
set packpath+=$XDG_CONFIG_HOME/vim/after,$XDG_DATA_HOME/vim/after

let g:netrw_home = $XDG_DATA_HOME."/vim"
call mkdir($XDG_DATA_HOME."/vim/spell", 'p')
set viewdir=$XDG_DATA_HOME/vim/view | call mkdir(&viewdir, 'p')

set backupdir=$XDG_CACHE_HOME/vim/backup | call mkdir(&backupdir, 'p')
set directory=$XDG_CACHE_HOME/vim/swap   | call mkdir(&directory, 'p')
set undodir=$XDG_CACHE_HOME/vim/undo     | call mkdir(&undodir,   'p')

if !has('nvim') | set viminfofile=$XDG_STATE_HOME/vim/viminfo | endif

" Install vim-plug if not found
if empty(system('echo -n "${XDG_CONFIG_HOME:-$HOME/.config}/vim/autoload/plug.vim"'))
  silent !curl -fLo $XDG_CONFIG_HOME/vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
endif

source $XDG_CONFIG_HOME/vim/plug-config/plugins.vim
source $XDG_CONFIG_HOME/vim/general/basic.vim

" Keybindings
source $XDG_CONFIG_HOME/vim/keys/fzf.vim
source $XDG_CONFIG_HOME/vim/keys/goyo.vim
source $XDG_CONFIG_HOME/vim/keys/splits.vim
source $XDG_CONFIG_HOME/vim/keys/shell.vim

" Plugin configs
" source $XDG_CONFIG_HOME/vim/plug-config/coc.vim
" source $XDG_CONFIG_HOME/vim/plug-config/netrw.vim
source $XDG_CONFIG_HOME/vim/plug-config/vimwiki.vim
