#!/bin/sh

# This file runs when a DM logs you into a graphical session.
# If you use startx/xinit like a Chad, this file will also be sourced.


doas rfkill unblock wifi &
xrdb -merge ${XDG_CONFIG_HOME:-$HOME/.config}/x11/Xresources &
xset r rate 300 50 &									# Speed xrate up
xsetroot -cursor_name left_ptr &
# xhost +local: &
(sleep 1s && xwallpaper-random) &
