#!/bin/sh

# This file runs when a DM logs you into a graphical session.
# If you use startx/xinit like a Chad, this file will also be sourced.

# xrdb -merge ${XDG_CONFIG_HOME:-$HOME/.config}/x11/Xresources &	# use options from Xresources
# xsetroot -cursor_name left_ptr &			# Fix The Cursor
# xset r rate 300 50 &									# Speed xrate up
# xhost +local: &												# This is for my void-glibc chroot
# dpms-toggle &													# disable DPMS
# alsa-bt-control &
# xwallpaper-random &										# Choose a random wallpaper and use xwallpaper to set it
