#!/bin/sh

bspc rule -r "*"

pgrep -x sxhkd > /dev/null || sxhkd &
# pgrep -x polybar > /dev/null || launchpolybar

# pgrep -x succade > /dev/null || succade &

# pkill -x polybar &
# launchpolybar &

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width        2
bspc config window_gap          6
bspc config top_padding					0

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Dracula
bspc config normal_border_color "#44475a"
bspc config active_border_color "#bd93f9"
bspc config focused_border_color "#ff79c6"
bspc config presel_feedback_color "#6272a4"


# Rules
bspc rule -a Gimp desktop='^4' state=floating follow=on
bspc rule -a Chromium desktop='^6'
bspc rule -a Firefox desktop='^6'
bspc rule -a mplayer2 state=floating
bspc rule -a mpv desktop='^5' state=fullscreen
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
