#!/bin/sh

bspc rule -r "*"

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9

###---Global Settings---###
bspc config automatic_scheme alternate
bspc config initial_polarity second_child
bspc config pointer_modifier lock
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config click_to_focus none

bspc config focus_follows_pointer true
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true

bspc config normal_border_color	"#4c566a"
bspc config active_border_color	"#1e1e1e"
bspc config focused_border_color "#327bd1"
bspc config presel_feedback_color "#327bd1"
bspc config urgent_border_color "#dd2727"

###---Monitor And Desktop Settings----###
bspc config top_padding 0
bspc config bottom_padding 0
bspc config left_padding 0
bspc config right_padding 0
bspc config border_width 2
bspc config window_gap 10

# Dracula
# bspc config normal_border_color "#44475a"
# bspc config active_border_color "#bd93f9"
# bspc config focused_border_color "#ff79c6"
# bspc config presel_feedback_color "#6272a4"


# Rules
bspc rule -a Gimp desktop='^4' state=floating follow=on
bspc rule -a Chromium desktop='^6'
bspc rule -a Chromium-browser desktop='^6'
bspc rule -a Firefox desktop='^6'
bspc rule -a mplayer2 state=floating
bspc rule -a mpv desktop='^5' state=fullscreen
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
